# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'config_edit_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Config_edit_window(object):
    def setupUi(self, Config_edit_window):
        Config_edit_window.setObjectName("Config_edit_window")
        Config_edit_window.resize(600, 450)
        self.verticalLayoutWidget = QtWidgets.QWidget(Config_edit_window)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 581, 411))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.layout.setContentsMargins(0, 0, 0, 0)
        self.layout.setObjectName("layout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.layout.addWidget(self.label)
        self.config_edit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.config_edit.setObjectName("config_edit")
        self.layout.addWidget(self.config_edit)
        self.btns_layout = QtWidgets.QHBoxLayout()
        self.btns_layout.setObjectName("btns_layout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.btns_layout.addItem(spacerItem)
        self.cancel_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.cancel_btn.setObjectName("cancel_btn")
        self.btns_layout.addWidget(self.cancel_btn)
        self.save_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.save_btn.setObjectName("save_btn")
        self.btns_layout.addWidget(self.save_btn)
        self.layout.addLayout(self.btns_layout)

        self.retranslateUi(Config_edit_window)
        QtCore.QMetaObject.connectSlotsByName(Config_edit_window)

    def retranslateUi(self, Config_edit_window):
        _translate = QtCore.QCoreApplication.translate
        Config_edit_window.setWindowTitle(_translate("Config_edit_window", "Настройка конфигурации"))
        self.label.setText(_translate("Config_edit_window", "Настройка конфигурации"))
        self.cancel_btn.setText(_translate("Config_edit_window", "Отмена"))
        self.save_btn.setText(_translate("Config_edit_window", "Сохранить"))
