# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 250)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 30, 322, 201))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.layout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.layout.setContentsMargins(0, 0, 0, 0)
        self.layout.setHorizontalSpacing(10)
        self.layout.setVerticalSpacing(8)
        self.layout.setObjectName("layout")
        self.multiplied_number_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.multiplied_number_label.setText("")
        self.multiplied_number_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.multiplied_number_label.setObjectName("multiplied_number_label")
        self.layout.addWidget(self.multiplied_number_label, 5, 1, 1, 1)
        self.miltiplied_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.miltiplied_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.miltiplied_label.setObjectName("miltiplied_label")
        self.layout.addWidget(self.miltiplied_label, 5, 0, 1, 1)
        self.number_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.number_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.number_label.setObjectName("number_label")
        self.layout.addWidget(self.number_label, 4, 0, 1, 1)
        self.number_line_edit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.number_line_edit.setEnabled(False)
        self.number_line_edit.setObjectName("number_line_edit")
        self.layout.addWidget(self.number_line_edit, 4, 1, 1, 1)
        self.server_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.server_label.setObjectName("server_label")
        self.layout.addWidget(self.server_label, 2, 0, 1, 1)
        self.multiply_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.multiply_btn.setEnabled(False)
        self.multiply_btn.setObjectName("multiply_btn")
        self.layout.addWidget(self.multiply_btn, 6, 1, 1, 1)
        self.address_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.address_label.setText("")
        self.address_label.setObjectName("address_label")
        self.layout.addWidget(self.address_label, 2, 1, 1, 1)
        self.connect_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.connect_btn.setObjectName("connect_btn")
        self.layout.addWidget(self.connect_btn, 3, 1, 1, 1)
        self.name_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.name_label.setFont(font)
        self.name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.name_label.setObjectName("name_label")
        self.layout.addWidget(self.name_label, 0, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layout.addItem(spacerItem, 1, 0, 1, 2)
        self.settings_btn = QtWidgets.QToolButton(self.centralwidget)
        self.settings_btn.setGeometry(QtCore.QRect(360, 10, 30, 30))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/gear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settings_btn.setIcon(icon)
        self.settings_btn.setObjectName("settings_btn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Удвоитель чисел"))
        self.miltiplied_label.setText(_translate("MainWindow", "Удвоенное число:"))
        self.number_label.setText(_translate("MainWindow", "Число:"))
        self.server_label.setText(_translate("MainWindow", "Сервер:"))
        self.multiply_btn.setText(_translate("MainWindow", "Удвоить"))
        self.connect_btn.setText(_translate("MainWindow", "Подключиться"))
        self.name_label.setText(_translate("MainWindow", "Великий удвоитель"))
        self.settings_btn.setText(_translate("MainWindow", "..."))
import resources.resources
